package io.nuls.db.entity;

public class ConsensusAccountPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consensus_account.hash
     *
     * @mbg.generated
     */
    private String hash;
    private int role;
    private int status;
    private long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consensus_account.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consensus_account.agent_address
     *
     * @mbg.generated
     */
    private String agentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consensus_account.deposit
     *
     * @mbg.generated
     */
    private Double deposit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consensus_account.hash
     *
     * @return the value of consensus_account.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consensus_account.hash
     *
     * @param hash the value for consensus_account.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consensus_account.address
     *
     * @return the value of consensus_account.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consensus_account.address
     *
     * @param address the value for consensus_account.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consensus_account.agent_address
     *
     * @return the value of consensus_account.agent_address
     *
     * @mbg.generated
     */
    public String getAgentAddress() {
        return agentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consensus_account.agent_address
     *
     * @param agentAddress the value for consensus_account.agent_address
     *
     * @mbg.generated
     */
    public void setAgentAddress(String agentAddress) {
        this.agentAddress = agentAddress == null ? null : agentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consensus_account.deposit
     *
     * @return the value of consensus_account.deposit
     *
     * @mbg.generated
     */
    public Double getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consensus_account.deposit
     *
     * @param deposit the value for consensus_account.deposit
     *
     * @mbg.generated
     */
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }
}