package io.nuls.db.entity;

/**
 * @author Niels
 * @date 2017/11/20
 */
public class PeerPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.last_time
     *
     * @mbg.generated
     */
    private Long lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.heart_faild_count
     *
     * @mbg.generated
     */
    private Integer failCount;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.magic_num
     *
     * @mbg.generated
     */
    private Integer magicNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer.version
     *
     * @mbg.generated
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.id
     *
     * @return the value of peer.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.id
     *
     * @param id the value for peer.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.ip
     *
     * @return the value of peer.ip
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.ip
     *
     * @param ip the value for peer.ip
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.port
     *
     * @return the value of peer.port
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.port
     *
     * @param port the value for peer.port
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.last_time
     *
     * @return the value of peer.last_time
     * @mbg.generated
     */
    public Long getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.last_time
     *
     * @param lastTime the value for peer.last_time
     * @mbg.generated
     */
    public void setLastTime(Long lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.magic_num
     *
     * @return the value of peer.magic_num
     * @mbg.generated
     */
    public Integer getMagicNum() {
        return magicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.magic_num
     *
     * @param magicNum the value for peer.magic_num
     * @mbg.generated
     */
    public void setMagicNum(Integer magicNum) {
        this.magicNum = magicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer.version
     *
     * @return the value of peer.version
     * @mbg.generated
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer.version
     *
     * @param version the value for peer.version
     * @mbg.generated
     */
    public void setVersion(Short version) {
        this.version = version;
    }

    public Integer getFailCount() {
        return failCount;
    }

    public void setFailCount(Integer failCount) {
        this.failCount = failCount;
    }
}