package io.nuls.db.entity;

public class PeerGroupRelationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer_group_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer_group_relation.peer_id
     *
     * @mbg.generated
     */
    private Integer peerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column peer_group_relation.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer_group_relation.id
     *
     * @return the value of peer_group_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer_group_relation.id
     *
     * @param id the value for peer_group_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer_group_relation.peer_id
     *
     * @return the value of peer_group_relation.peer_id
     *
     * @mbg.generated
     */
    public Integer getPeerId() {
        return peerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer_group_relation.peer_id
     *
     * @param peerId the value for peer_group_relation.peer_id
     *
     * @mbg.generated
     */
    public void setPeerId(Integer peerId) {
        this.peerId = peerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column peer_group_relation.group_id
     *
     * @return the value of peer_group_relation.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column peer_group_relation.group_id
     *
     * @param groupId the value for peer_group_relation.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}