package io.nuls.db.entity;

public class UtxoOutputPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.value
     *
     * @mbg.generated
     */
    private Double value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.lock_time
     *
     * @mbg.generated
     */
    private Long lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.out_index
     *
     * @mbg.generated
     */
    private Integer outIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utxo_output.script
     *
     * @mbg.generated
     */
    private byte[] script;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.hash
     *
     * @return the value of utxo_output.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.hash
     *
     * @param hash the value for utxo_output.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.tx_hash
     *
     * @return the value of utxo_output.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.tx_hash
     *
     * @param txHash the value for utxo_output.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.value
     *
     * @return the value of utxo_output.value
     *
     * @mbg.generated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.value
     *
     * @param value the value for utxo_output.value
     *
     * @mbg.generated
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.lock_time
     *
     * @return the value of utxo_output.lock_time
     *
     * @mbg.generated
     */
    public Long getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.lock_time
     *
     * @param lockTime the value for utxo_output.lock_time
     *
     * @mbg.generated
     */
    public void setLockTime(Long lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.status
     *
     * @return the value of utxo_output.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.status
     *
     * @param status the value for utxo_output.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.out_index
     *
     * @return the value of utxo_output.out_index
     *
     * @mbg.generated
     */
    public Integer getOutIndex() {
        return outIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.out_index
     *
     * @param outIndex the value for utxo_output.out_index
     *
     * @mbg.generated
     */
    public void setOutIndex(Integer outIndex) {
        this.outIndex = outIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.address
     *
     * @return the value of utxo_output.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.address
     *
     * @param address the value for utxo_output.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utxo_output.script
     *
     * @return the value of utxo_output.script
     *
     * @mbg.generated
     */
    public byte[] getScript() {
        return script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utxo_output.script
     *
     * @param script the value for utxo_output.script
     *
     * @mbg.generated
     */
    public void setScript(byte[] script) {
        this.script = script;
    }
}