package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.dao.impl.mybatis.common.BaseMapper;
import io.nuls.db.entity.AliasPo;

public interface AliasMapper extends BaseMapper<String, AliasPo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    int deleteByPrimaryKey(String alias);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    int insert(AliasPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    int insertSelective(AliasPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    AliasPo selectByPrimaryKey(String alias);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    int updateByPrimaryKeySelective(AliasPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated Wed Dec 13 16:27:33 CST 2017
     */
    int updateByPrimaryKey(AliasPo record);
}