package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.BlockPo;

public interface BlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int insert(BlockPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int insertSelective(BlockPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    BlockPo selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlockPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BlockPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlockPo record);
}