package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.ConsensusAccountPo;

public interface ConsensusAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    int insert(ConsensusAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    int insertSelective(ConsensusAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    ConsensusAccountPo selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConsensusAccountPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consensus_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsensusAccountPo record);
}