package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.PeerGroupPo;

public interface PeerGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    int insert(PeerGroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    int insertSelective(PeerGroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    PeerGroupPo selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PeerGroupPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PeerGroupPo record);
}