package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.PeerPo;

public interface PeerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    int insert(PeerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    int insertSelective(PeerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    PeerPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PeerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PeerPo record);
}