package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.PeerGroupRelationPo;

public interface PeerGroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    int insert(PeerGroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    int insertSelective(PeerGroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    PeerGroupRelationPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PeerGroupRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table peer_group_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PeerGroupRelationPo record);
}