package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.SubChainPo;

public interface SubChainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int insert(SubChainPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int insertSelective(SubChainPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    SubChainPo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SubChainPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SubChainPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_chain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubChainPo record);
}