package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.TransactionLocalPo;

public interface TransactionLocalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int insert(TransactionLocalPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int insertSelective(TransactionLocalPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    TransactionLocalPo selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransactionLocalPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TransactionLocalPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_local
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransactionLocalPo record);
}