package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.TxAccountRelationPo;

public interface TxAccountRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    int insert(TxAccountRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    int insertSelective(TxAccountRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    TxAccountRelationPo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TxAccountRelationPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_account_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TxAccountRelationPo record);
}