package io.nuls.db.dao.impl.mybatis.mapper;

import io.nuls.db.entity.UtxoOutputPo;

public interface UtxoOutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int insert(UtxoOutputPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int insertSelective(UtxoOutputPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    UtxoOutputPo selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UtxoOutputPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UtxoOutputPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utxo_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UtxoOutputPo record);
}