package io.nuls.db.dao.intf.mybatis.mapper;

import java.util.List;

/**
 * Created by Niels on 2017/11/22.
 */
public interface BaseMapper<K,V> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(K key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int insert(V record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int insertSelective(V record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    V selectByPrimaryKey(K key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(V record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(V record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(V record);

    int batchInsert(List<V> records);

    List<V> selectAll();
}
