package io.nuls.account.storage.po;

import io.nuls.account.model.Account;
import io.nuls.kernel.model.BaseNulsData;
import io.protostuff.Tag;

/**
 * @author: Charlie
 * @date: 2018/5/9
 */
public class AccountPo extends BaseNulsData {

    @Tag(1)
    private String address;
    @Tag(2)
    private Long createTime;
    @Tag(3)
    private String alias;
    @Tag(4)
    private byte[] pubKey;
    @Tag(5)
    private byte[] priKey;
    @Tag(6)
    private byte[] encryptedPriKey;
    @Tag(7)
    private byte[] extend;
    @Tag(8)
    private int status;

    public AccountPo(Account account){
        this.address = account.getAddress().toString();
        this.createTime = account.getCreateTime();
        this.alias = account.getAlias();
        this.pubKey = account.getPubKey();
        this.priKey = account.getPriKey();
        this.encryptedPriKey = account.getEncryptedPriKey();
        this.extend = account.getExtend();
        this.status = account.getStatus();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.address
     *
     * @return the value of account.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.address
     *
     * @param address the value for account.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.alias
     *
     * @return the value of account.alias
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.alias
     *
     * @param alias the value for account.alias
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.EXTEND
     *
     * @return the value of account.EXTEND
     * @mbg.generated
     */
    public byte[] getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.EXTEND
     *
     * @param extend the value for account.EXTEND
     * @mbg.generated
     */
    public void setExtend(byte[] extend) {
        this.extend = extend;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public byte[] getPriKey() {
        return priKey;
    }

    public void setPriKey(byte[] priKey) {
        this.priKey = priKey;
    }

    public byte[] getPubKey() {
        return pubKey;
    }

    public void setPubKey(byte[] pubKey) {
        this.pubKey = pubKey;
    }

    public byte[] getEncryptedPriKey() {
        return encryptedPriKey;
    }

    public void setEncryptedPriKey(byte[] encryptedPriKey) {
        this.encryptedPriKey = encryptedPriKey;
    }


}
